#!/usr/bin/env php
<?php
// application.php

require __DIR__.'/vendor/autoload.php';

use App\Command\CreateProject;
use Symfony\Component\Console\Application;

define('APP_VERSION', '1.0.0');
define('APP_FOLDER', dirname(__FILE__));

$application = new Application('WordPress Project Generator', APP_VERSION);

// ... register commands
$application->add(new CreateProject);

$application->run();

